name: Setup Node & Install dependencies

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # pin@v4.0.0
      with:
        version: 10.2.0

    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # pin@v4.2.0
      with:
        node-version-file: ".nvmrc"
        registry-url: https://registry.npmjs.org
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
